POST {{baseUrl}}/user/{{otherUserId}}/request/{{requestId}}/response
Content-Type: application/json
Authorization: Bearer {{anotherToken}}

{
    // Can be Accepted - 2, Refused - 3, Ignored - 4, Blocked - 5
    "Response": 2
}
