
services:
    db:
        container_name: db
        image: postgres:latest
        volumes:
            - ./.data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: teste@123
            POSTGRES_USER: user
            POSTGRES_DB: codegodev
        ports:
            - "5432:5432"
        restart: always
        networks:
            - codegodev-network
    app:
        container_name: app
        build: .
        environment:
            - ASPNETCORE_HTTP_PORT=https://+:2601
            - ASPNETCORE_URLS=http://+:2600
        env_file: .env
        ports:
            - "2600:2600"
            - "2601:2601"
        restart: always
        networks:
            - codegodev-network
        depends_on:
            - db
networks:
    codegodev-network:
        driver: bridge
