POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "FirstName": "Lucas Augusto",
    "LastName": "Silva",
    "Email": "lucas@email.com",
    "Password": "lucas@1234"
}

###

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "FirstName": "Guilherme Arthur Leimann",
    "LastName": "Illescas",
    "Email": "guilherme@email.com",
    "Password": "guilherme@1234"
}
