POST {{baseUrl}}/course/{{courseId}}/module
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sectionId": "{{sectionId}}",
    "name": "Declaração de Variavéis",
    "totalLessons": 4,
    "moduleTypeValue": 1,
    "difficulty": 1
}
