POST {{baseUrl}}/course/{{courseId}}/section
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Seção 1",
    "description": "Básico do Javascript"
}

###

POST {{baseUrl}}/course/{{courseId}}/section
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Seção 2",
    "description": "Avançando nos conceitos"
}
