POST {{baseUrl}}/lesson/{{lessonId}}/resolve/question
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "questionId": "eb939990-0d6a-45e0-bb70-b4bd1f841326",
    "alternativeId": "2c4a6f77-b1df-4e0a-93c9-1934f5fc8082"
}
