@lessonId = 17b33c88-0b01-4aaf-a8e5-15eb0e92980f

PUT {{baseUrl}}/lesson/{{lessonId}}/resolve/question
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "questionId": "eb939990-0d6a-45e0-bb70-b4bd1f841326",
    "alternativeId": "446d057e-fb5a-4adc-9576-7aceb2ebf94f"
}

###

PUT {{baseUrl}}/lesson/{{lessonId}}/resolve/question
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "questionId": "54ab17cf-2cc9-42fe-b59c-5cf04158e547",
    "alternativeId": "6268b9bf-4f5c-42dd-a4f7-d8aca2860f2c"
}
