name: Deploy Prod

on:
  workflow_run:
    workflows: [Dotnet Build and Test]
    types: [completed]
    branches: [master]

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Migrate DB
        shell: pwsh
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet-ef database update 0 --project "CodeGo.Infrastructure\CodeGo.Infrastructure.csproj" --startup-project "CodeGo.Api\CodeGo.Api.csproj" --context CodeGoDbContext --connection "${{secrets.DATABASE_CONNECTION_STRING}}"

  deploy:
    needs: migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "code-go" #Must be unique in Heroku
          heroku_email: "silvaaugustolucas@gmail.com"
          usedocker: true
