name: Deploy Prod

on:
  workflow_run:
    workflows: [Dotnet Build and Test]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "code-go" #Must be unique in Heroku
          heroku_email: "silvaaugustolucas@gmail.com"
          usedocker: true
